In [1]:
import pandas as pd
import gzip
import re
import tarfile
import io
from tqdm import tqdm

from pysradb.sraweb import SRAweb

/home/galvanized_heart/.local/lib/python3.10/site-packages/pysradb/utils.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

# Investigate GEO datasets
In this notebook, we will be looking at data from `Himes BE, Jiang X, Wagner P, Hu R, Wang Q, Klanderman B, Whitaker RM, Duan Q, Lasky-Su J, Nikolos C, Jester W, Johnson M, Panettieri R Jr, Tantisira KG, Weiss ST, Lu Q. “RNA-Seq Transcriptome Profiling Identifies CRISPLD2 as a Glucocorticoid Responsive Gene that Modulates Cytokine Function in Airway Smooth Muscle Cells.” PLoS One. 2014 Jun 13;9(6):e99625. PMID: 24926665. GEO: GSE52778.` and we'll be building a csv for the number of transcript counts for each experiment and metadata to map experiments to their conditions. The data (`airway_1.28.0.tar.gz`, `GSE52778_raw_counts_GRCh38.p13_NCBI.tsv.gz`, `GSE52778_series_matrix.txt.gz`, and `Human.GRCh38.p13.annot.tsv.gz`) can be downloaded from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52778 

Given datasets (`airway_rawcounts.csv` and `airway_metadata.csv`) were sourced from https://4va.github.io/biodatasci/r-rnaseq-airway.html

In [2]:
series_matrix_file_gz = "GSE52778_series_matrix.txt.gz"
sample_count_to_inspect = 3 
samples_inspected = 0

print(f"--- Inspecting: {series_matrix_file_gz} ---")

with gzip.open(series_matrix_file_gz, 'rt') as f:
    for line in f:
        line = line.strip()
        if line.startswith("!Sample_geo_accession"):
            if samples_inspected >= sample_count_to_inspect:
                break
            samples_inspected += 1
            print("\n--- New Sample ---")
            print(line)
        elif samples_inspected > 0 and samples_inspected <= sample_count_to_inspect:
            if line.startswith("!Sample_title") or \
               line.startswith("!Sample_characteristics_ch1") or \
               line.startswith("!Sample_relation"): # SRA relations often hold SRR
                print(line)
        if line.startswith("!series_matrix_table_begin"): # Stop before the data table
            break

--- Inspecting: GSE52778_series_matrix.txt.gz ---

--- New Sample ---
!Sample_geo_accession	"GSM1275862"	"GSM1275863"	"GSM1275864"	"GSM1275865"	"GSM1275866"	"GSM1275867"	"GSM1275868"	"GSM1275869"	"GSM1275870"	"GSM1275871"	"GSM1275872"	"GSM1275873"	"GSM1275874"	"GSM1275875"	"GSM1275876"	"GSM1275877"
!Sample_characteristics_ch1	"treatment: Untreated"	"treatment: Dexamethasone"	"treatment: Albuterol"	"treatment: Albuterol_Dexamethasone"	"treatment: Untreated"	"treatment: Dexamethasone"	"treatment: Albuterol"	"treatment: Albuterol_Dexamethasone"	"treatment: Untreated"	"treatment: Dexamethasone"	"treatment: Albuterol"	"treatment: Albuterol_Dexamethasone"	"treatment: Untreated"	"treatment: Dexamethasone"	"treatment: Albuterol"	"treatment: Albuterol_Dexamethasone"
!Sample_characteristics_ch1	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"	"tissue: human airway smooth muscle cells"
!Sample_characteristics_ch1	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: 1"	"ercc_mix: 1"	"ercc_mix: 1"	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: -"	"ercc_mix: 1"	"ercc_mix: 1"	"ercc_mix: 1"	"ercc_mix: 1"
!Sample_characteristics_ch1	"cell line: N61311"	"cell line: N61311"	"cell line: N61311"	"cell line: N61311"	"cell line: N052611"	"cell line: N052611"	"cell line: N052611"	"cell line: N052611"	"cell line: N080611"	"cell line: N080611"	"cell line: N080611"	"cell line: N080611"	"cell line: N061011"	"cell line: N061011"	"cell line: N061011"	"cell line: N061011"
!Sample_characteristics_ch1	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"	"cell type: airway smooth muscle cells"
!Sample_relation	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422669"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422675"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422668"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422667"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422678"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422670"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422681"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422671"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422682"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422673"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422679"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422672"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422683"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422677"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422680"	"BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN02422674"
!Sample_relation	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384345"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384346"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384347"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384348"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384349"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384350"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384351"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384352"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384353"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384354"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384355"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384356"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384357"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384358"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384359"	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX384360"

In [3]:
raw_counts_file_gz = "GSE52778_raw_counts_GRCh38.p13_NCBI.tsv.gz"
lines_to_inspect = 10

print(f"\n--- Inspecting: {raw_counts_file_gz} ---")

with gzip.open(raw_counts_file_gz, 'rt') as f:
    for i, line in enumerate(f):
        if i >= lines_to_inspect:
            break
        print(f"Line {i+1}: {line.strip()}")

--- Inspecting: GSE52778_raw_counts_GRCh38.p13_NCBI.tsv.gz ---
Line 1: GeneID	GSM1275862	GSM1275863	GSM1275864	GSM1275865	GSM1275866	GSM1275867	GSM1275868	GSM1275869	GSM1275870	GSM1275871	GSM1275872	GSM1275873	GSM1275874	GSM1275875	GSM1275876	GSM1275877
Line 2: 100287102	6	8	8	3	5	10	11	7	6	8	4	10	2	1	2	2
Line 3: 653635	357	292	351	285	469	428	523	442	367	415	404	354	371	381	367	341
Line 4: 102466751	12	11	12	10	15	15	19	15	9	11	18	9	10	9	12	6
Line 5: 107985730	1	1	2	1	3	2	2	3	1	1	1	1	2	1	1	1
Line 6: 100302278	0	0	1	0	0	0	1	1	0	0	1	0	0	0	0	1
Line 7: 645520	7	2	4	4	6	2	3	6	2	2	3	6	6	3	8	3
Line 8: 79501	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
Line 9: 100996442	24	22	30	25	46	41	47	48	27	27	25	27	57	35	46	30
Line 10: 729737	50	38	46	40	118	124	137	122	43	56	60	43	78	70	79	68

In [4]:
annot = "Human.GRCh38.p13.annot.tsv.gz"
lines_to_inspect = 10

print(f"\n--- Inspecting: {annot} ---")

with gzip.open(annot, 'rt') as f:
    for i, line in enumerate(f):
        if i >= lines_to_inspect:
            break
        print(f"Line {i+1}: {line.strip()}")

--- Inspecting: Human.GRCh38.p13.annot.tsv.gz ---
Line 1: GeneID	Symbol	Description	Synonyms	GeneType	EnsemblGeneID	Status	ChrAcc	ChrStart	ChrStop	Orientation	Length	GOFunctionID	GOProcessID	GOComponentID	GOFunction	GOProcess	GOComponent
Line 2: 100287102	DDX11L1	DEAD/H-box helicase 11 like 1 (pseudogene)		pseudo	ENSG00000290825	active	NC_000001.11	11874	14409	positive	1652
Line 3: 653635	WASH7P	WASP family homolog 7, pseudogene	FAM39F|WASH5P	pseudo		active	NC_000001.11	14362	29370	negative	1769
Line 4: 102466751	MIR6859-1	microRNA 6859-1	hsa-mir-6859-1	ncRNA	ENSG00000278267	active	NC_000001.11	17369	17436	negative	68
Line 5: 107985730	MIR1302-2HG	MIR1302-2 host gene		ncRNA		active	NC_000001.11	29926	31295	positive	538
Line 6: 100302278	MIR1302-2	microRNA 1302-2	MIRN1302-2|hsa-mir-1302-2	ncRNA	ENSG00000284332	active	NC_000001.11	30366	30503	positive	138		GO:0035195			miRNA-mediated gene silencing
Line 7: 645520	FAM138A	family with sequence similarity 138 member A	F379|FAM138F	ncRNA	ENSG00000237613	active	NC_000001.11	34611	36081	negative	1130
Line 8: 79501	OR4F5	olfactory receptor family 4 subfamily F member 5		protein-coding	ENSG00000186092	active	NC_000001.11	69091	70008	positive	918	GO:0004930///GO:0004984	GO:0007186///GO:0050911	GO:0005886	G protein-coupled receptor activity///olfactory receptor activity	G protein-coupled receptor signaling pathway///detection of chemical stimulus involved in sensory perception of smell	plasma membrane
Line 9: 100996442	LOC100996442	WAS protein family homolog 2-like		ncRNA		active	NC_000001.11	89006	267354	negative	4894
Line 10: 729737	LOC729737	uncharacterized LOC729737		ncRNA		active	NC_000001.11	134773	140566	negative	5474

In [5]:
airway = "airway_1.28.0.tar.gz"
lines_to_inspect = 10

print(f"\n--- Inspecting contents of: {airway} ---")

# Open the gzipped file in binary mode ('rb') for tarfile
with gzip.open(airway, 'rb') as gz_file:
    # Open the tar archive from the decompressed gzip stream
    # 'r:' means read with transparent compression (auto-detects based on stream)
    # but since we already used gzip.open, 'r' or 'r:*' is fine.
    # Using 'r:' or 'r|*' is more general if tarfile itself handles gz.
    with tarfile.open(fileobj=gz_file, mode='r:') as tar_archive:
        print("Files in the archive:")
        members = tar_archive.getmembers()
        if not members:
            print("Archive is empty.")

        for member in members:
            print(f"  - {member.name} {'(Directory)' if member.isdir() else ''}")

            # If you want to inspect a specific file or all regular files:
            if member.isfile(): # Check if it's a regular file
                print(f"\n--- Inspecting first {lines_to_inspect} lines of {member.name} within {airway} ---")
                # Extract the file as a file-like object (binary stream)
                extracted_file_binary = tar_archive.extractfile(member)
                if extracted_file_binary: # Make sure extraction was successful
                    # Wrap the binary stream in a TextIOWrapper to read as text
                    # Use an encoding you expect, or 'utf-8' with error handling
                    try:
                        with io.TextIOWrapper(extracted_file_binary, encoding='utf-8', errors='replace') as text_f:
                            for i, line in enumerate(text_f):
                                if i >= lines_to_inspect:
                                    break
                                print(f"  Line {i+1}: {line.strip()}")
                    except UnicodeDecodeError as ude:
                        print(f"    Could not decode {member.name} as UTF-8: {ude}")
                        print(f"    It might be a binary file or use a different encoding.")
                    except Exception as e_inner:
                        print(f"    Error reading {member.name}: {e_inner}")
                else:
                    print(f"    Could not extract {member.name} for inspection.")
            print("---") # Separator between files

--- Inspecting contents of: airway_1.28.0.tar.gz ---
Files in the archive:
  - airway/DESCRIPTION

--- Inspecting first 10 lines of airway/DESCRIPTION within airway_1.28.0.tar.gz ---
  Line 1: Package: airway
  Line 2: Title: RangedSummarizedExperiment for RNA-Seq in airway smooth muscle
  Line 3: cells, by Himes et al PLoS One 2014
  Line 4: Version: 1.28.0
  Line 5: Author: Michael Love
  Line 6: Maintainer: Michael Love <michaelisaiahlove@gmail.com>
  Line 7: Description: This package provides a RangedSummarizedExperiment object
  Line 8: of read counts in genes for an RNA-Seq experiment on four human
  Line 9: airway smooth muscle cell lines treated with dexamethasone.
  Line 10: Details on the gene model and read counting procedure are
---
  - airway/NAMESPACE

--- Inspecting first 10 lines of airway/NAMESPACE within airway_1.28.0.tar.gz ---
  Line 1: exportPattern(".")
---
  - airway/build (Directory)
---
  - airway/build/vignette.rds

--- Inspecting first 10 lines of airway/build/vignette.rds within airway_1.28.0.tar.gz ---
  Line 1:       ��b```b`a��@&�0�`b fd`a��\��E剕zA�)h2R�`�����������T��Ԝ�b4��P32JrsФ8`�� ���:ּ��Tts�]RR�R@����g��n�wjey~L�6��̜T��!�%ps�������Q��Y�_��/(��� @�hrNb1�G�RK�Ҋ��A� L8�y�  
---
  - airway/data (Directory)
---
  - airway/data/airway.RData

--- Inspecting first 10 lines of airway/data/airway.RData within airway_1.28.0.tar.gz ---
  Line 1: �7zXZ  i"�6 !   �X��(��] )Th�nRʠ3�$^�k�׋S7�қ�*�������`K���[���R��)|f�,0�fVA�]]=��
  Line 2: �˟}��A��vԧ�e�KXg�
  Line 3: v�� �ఆ|�+���'>�"
  Line 4: ;����M�Cx_��I��]ͮ>ȵ`�@�r��,
  Line 5: �7��E�6��unC�g_��g�n\D*�"�/��܌ʍ��,�5ݗ�\);��
  Line 6: ���F�z!�\F��mB�?�������FҎ�LP��U�<�?�6#���R2��֐6���s!0�&��k���K�TR�bI�dl*Dх�cbS�k~�#槣U�[����)l\���ΟpC����x�1i��|��b���zJ�k����<�%��Ԥp����H<�q���F���`�xt�#�l�G�r2��WB���2�����+@�io������f$_j	���jSF�$]�`"+��� ���#%L�5D�gW��"���'���s|~a���#��G���w�w��&
  Line 7: ��y��pz�v"�F����O���B(1���媂ս�E�^zX�H)I:�� �Z�}�_�5�6�B�d��k��h�\�4r�N��{��K���>��u��h�Fv�lOH�F_Y8�:>�vS�Cn�~�q��t����/&��7!�b��Na��^^�Co��%�S��$��$�������&�ܦ���X����B2)���SR��'/�ֈB��7���5x
  Line 8: \Ǌ����w��r��Q
  Line 9: xL+���THf;�d����𸲺���^M��I�X�C�5�$�Ű�n���	�{�w��Ᏸa��I~�9���l��^Z�o�l�Lc?�
  Line 10: w�����=�MG����x�H�.�*/x����c3���7���L�IO���6�vW�A�J�o���/P�mͷ_�I��I���.�=0�������?���h�,Ґ���&)2���� ޝ�g*@��e)�G3W��i��є��\�/�	�0q\w=� t���U
---
  - airway/data/datalist

--- Inspecting first 10 lines of airway/data/datalist within airway_1.28.0.tar.gz ---
  Line 1: airway
  Line 2: gse
  Line 3:
---
  - airway/data/gse.rda

--- Inspecting first 10 lines of airway/data/gse.rda within airway_1.28.0.tar.gz ---
  Line 1:       ��	�4_Z׉�\*������f٥�QQ�\PԦipi���VA���#�(�@Y\GD���D��qi��"�.�zAh�t}o|��DdVe-￣>������>��YΉ�_�������~)eVf�I�����|���a����̧/\Lʼ�*|��^Q&����{�}�o�E/{�'��u���׽�7��e�!}���/{�oz�I����?��>g?VㅧW��������ë���������ޱ��O�����>vUwv5������ޱ�9�j��c^^}o��p/΍����ht��/��|�:��K�W����ϙ�����8�xZ�R}�^\�j=;W��\m)�'�im��2|����q����j�ër�����+�9�?���B�'W�fc2��_��w5>׋0�����;U���������A�Ϟ�1-��^�-���ë��T���A�yiu�-���s�'kD'��]�yz�lr5擫v������>Y���s���iܓ���T��W�tp��L�c�����wv5��U]�?������>���V���g��rM,/��~vU���^g��uM���|q5�]�F������Wu��'Ws��`�ٻ��6�NKW��1p���K�[O��xZr^\����5ot|~�y�����唹O��ë�;Wes��)-��<�w�q\Z,+O��zt5��U]do�te
  Line 2: ځ]���U?�y��`�\��ݸ�_�}5N[ߡ)����K�GMi�[�_ZYA�7zO̟�2�'�Ρ����ښ�����]�y!;���=����u�D�jqU�y���l�-�3�	�_���ev5/h�*�J���w��Y�S�
  Line 3: M�t3V�Kk�A�Ws�}�v����`��өӔV���7�g��xvQZ���U�����D�F���S�k'|�\����>��}����1d
  Line 4: �M������ׂ���3�-x@����?�^j\�N��2�!p�z�PsEOlH#Z���J�y˙�z*Z7W��{pY~���k�7���k��l:R�ii�{�����
  Line 5: �M��������hM����'�C[p�����j<J|M�t|�!w�7v�3�U�|�7$���;�u��RZ,{R���yY#|����`�mP�v;���)]�C/J.?��q���yTZ�14��N��+���'W��1��yZZ�����r�.������.:�@S��Ʃyh7�����ڰ�ƻ�ҵ�	^@{|r�����9�g���`���~�U�>���+�=h��;)m\=S�u��_DϜ���؉�{\Z�F�B΅���
  Line 6: ������������wiJ+o��O�;1�ÿ�7�S}x�\�_��Fo�MJ��g������kG}��CN�g��X�Y��
  Line 7: d���¢��$2m_��j|b�hS�q�D��q߶��t�>/x�lڦ8��j�/	�����������t�e̗8�E�����l�gI��9���^�5��Ӊ�ή��ƸI	=й���+��C��X�]���
  Line 8: o��ax�-B�Oi�Q�.ؘh���$橈��A��xVZ��8>��vQZ�a���	�?�h���/��X���C�ӫu4��T�;��ĢMie���F���j�e|r�m�GW�Z�ׄO��G��g"w�=+-ߣ�Á�����m���~c����>`^SZ��x���WcnS�x�ytp�9!c{�~cC�/m�S�	����W��	��d���^8�}�a7�a���B9/]�ܖu�t���ݡ|Ư�+���Y�1:P}fN��-s;�����!x��#zv\��\}�j\��������Ι��O�鴴>���Dϸ?)m�żg�TZ,�́�
  Line 9: �1�q��s�e@ox���z�	c��0����=����n�[�z6-m��_Z���G�/ޫB��A�s��{J�{�[>��!W�\g|�8n0~��E�yLUY�P��3-��=�!|[�t|�N���7EG�i
  Line 10: ���:�x�q���n"K;Wc�3�������є�ύ�b��0���?�(�ڎ�:?}��߮�7�/�����&b
---
  - airway/external_data_store.txt

--- Inspecting first 10 lines of airway/external_data_store.txt within airway_1.28.0.tar.gz ---
  Line 1: data
  Line 2: inst/extdata
---
  - airway/inst (Directory)
---
  - airway/inst/CITATION

--- Inspecting first 10 lines of airway/inst/CITATION within airway_1.28.0.tar.gz ---
  Line 1: citEntry(entry="article",
  Line 2: Author="Himes, B. E.  and Jiang, X.  and Wagner, P.  and Hu, R.  and Wang, Q.  and Klanderman, B.  and Whitaker, R. M.  and Duan, Q.  and Lasky-Su, J.  and Nikolos, C.  and Jester, W.  and Johnson, M.  and Panettieri, R. A.  and Tantisira, K. G.  and Weiss, S. T.  and Lu, Q. ",
  Line 3: Title="{{R}{N}{A}-{S}eq {T}ranscriptome {P}rofiling {I}dentifies {C}{R}{I}{S}{P}{L}{D}2 as a {G}lucocorticoid {R}esponsive {G}ene that {M}odulates {C}ytokine {F}unction in {A}irway {S}mooth {M}uscle {C}ells}",
  Line 4: Journal="PLoS ONE",
  Line 5: Year="2014",
  Line 6: Volume="9",
  Line 7: Number="6",
  Line 8: Pages="e99625",
  Line 9: url = "http://www.ncbi.nlm.nih.gov/pubmed/24926665",
  Line 10: textVersion="Himes BE, Jiang X, Wagner P, Hu R, Wang Q, Klanderman B, Whitaker RM, Duan Q, Lasky-Su J, Nikolos C, Jester W, Johnson M, Panettieri R Jr, Tantisira KG, Weiss ST, Lu Q. 'RNA-Seq Transcriptome Profiling Identifies CRISPLD2 as a Glucocorticoid Responsive Gene that Modulates Cytokine Function in Airway Smooth Muscle Cells.' PLoS One. 2014 Jun 13;9(6):e99625. PMID: 24926665.")
---
  - airway/inst/doc (Directory)
---
  - airway/inst/doc/airway.R

--- Inspecting first 10 lines of airway/inst/doc/airway.R within airway_1.28.0.tar.gz ---
  Line 1: ## -----------------------------------------------------------------------------
  Line 2: suppressPackageStartupMessages( library( "GEOquery" ) )
  Line 3: suppressPackageStartupMessages( library( "airway" ) )
  Line 4: dir <- system.file("extdata",package="airway")
  Line 5: geofile <- file.path(dir, "GSE52778_series_matrix.txt")
  Line 6: gse <- getGEO(filename=geofile)
  Line 7: pdata <- pData(gse)[,grepl("ch1",names(pData(gse)))]
  Line 8: names(pdata) <- c("treatment","tissue","ercc_mix","cell","celltype")
  Line 9: pdataclean <- data.frame(treatment=sub("treatment: (.*)","\\1",pdata$treatment),
  Line 10: cell=sub("cell line: (.*)","\\1",pdata$cell),
---
  - airway/inst/doc/airway.Rmd

--- Inspecting first 10 lines of airway/inst/doc/airway.Rmd within airway_1.28.0.tar.gz ---
  Line 1: <!--
  Line 2: %\VignetteEngine{knitr::knitr}
  Line 3: %\VignetteIndexEntry{Airway smooth muscle cells}
  Line 4: -->
  Line 5:
  Line 6: # Airway smooth muscle cells
  Line 7:
  Line 8: Here we provide the code which was used to contruct the
  Line 9: *RangedSummarizedExperiment* object of the *airway* experiment data
  Line 10: package. The experiment citation is:
---
  - airway/inst/doc/airway.html

--- Inspecting first 10 lines of airway/inst/doc/airway.html within airway_1.28.0.tar.gz ---
  Line 1: <!DOCTYPE html>
  Line 2: <html>
  Line 3: <head>
  Line 4: <meta charset="utf-8">
  Line 5: <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  Line 6: <meta name="generator" content="litedown 0.7">
  Line 7: <title></title>
  Line 8: <style type="text/css">
  Line 9: body {
  Line 10: font-family: sans-serif;
---
  - airway/inst/extdata (Directory)
---
  - airway/inst/extdata/GSE52778_series_matrix.txt

--- Inspecting first 10 lines of airway/inst/extdata/GSE52778_series_matrix.txt within airway_1.28.0.tar.gz ---
  Line 1: !Series_title	"Human Airway Smooth Muscle Transcriptome Changes in Response to Asthma Medications"
  Line 2: !Series_geo_accession	"GSE52778"
  Line 3: !Series_status	"Public on Jan 01 2014"
  Line 4: !Series_submission_date	"Nov 26 2013"
  Line 5: !Series_last_update_date	"Jul 01 2014"
  Line 6: !Series_pubmed_id	"24926665"
  Line 7: !Series_summary	"Rationale: Asthma is a chronic inflammatory airway disease. The most common medications used for its treatment are β2-agonists and glucocorticosteroids, and one of the primary tissues that these drugs target in the treatment of asthma is the airway smooth muscle. We used RNA-Seq to characterize the human airway smooth muscle (HASM) transcriptome at baseline and under three asthma treatment conditions."
  Line 8: !Series_summary	"Methods: The Illumina TruSeq assay was used to prepare 75bp paired-end libraries for HASM cells from four white male donors under four treatment conditions: 1) no treatment; 2) treatment with a β2-agonist (i.e. Albuterol, 1μM for 18h); 3) treatment with a glucocorticosteroid (i.e. Dexamethasone (Dex), 1μM for 18h); 4) simultaneous treatment with a β2-agonist and glucocorticoid, and the libraries were sequenced with an Illumina Hi-Seq 2000 instrument. The Tuxedo Suite Tools were used to align reads to the hg19 reference genome, assemble transcripts, and perform differential expression analysis using the protocol described in https://github.com/blancahimes/taffeta"
  Line 9: !Series_overall_design	"mRNA profiles obtained via RNA-Seq for four primary human airway smooth muscle cell lines that were treated with dexamethasone, albuterol, dexamethasone+albuterol or were left untreated."
  Line 10: !Series_type	"Expression profiling by high throughput sequencing"
---
  - airway/inst/extdata/Homo_sapiens.GRCh37.75_subset.gtf

--- Inspecting first 10 lines of airway/inst/extdata/Homo_sapiens.GRCh37.75_subset.gtf within airway_1.28.0.tar.gz ---
  Line 1: #!genome-build GRCh37.p13
  Line 2: #!genome-version GRCh37
  Line 3: #!genome-date 2009-02
  Line 4: #!genome-build-accession NCBI:GCA_000001405.14
  Line 5: #!genebuild-last-updated 2013-09
  Line 6: #!manually subset to include only 1:11000001-11400000
  Line 7: 1	retained_intron	transcript	11006528	11009808	.	-	.	gene_id "ENSG00000175262"; transcript_id "ENST00000476357"; gene_name "C1orf127"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "C1orf127-002"; transcript_source "havana";
  Line 8: 1	retained_intron	exon	11007700	11009808	.	-	.	gene_id "ENSG00000175262"; transcript_id "ENST00000476357"; exon_number "1"; gene_name "C1orf127"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "C1orf127-002"; transcript_source "havana"; exon_id "ENSE00001869344";
  Line 9: 1	retained_intron	exon	11006528	11006795	.	-	.	gene_id "ENSG00000175262"; transcript_id "ENST00000476357"; exon_number "2"; gene_name "C1orf127"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "C1orf127-002"; transcript_source "havana"; exon_id "ENSE00001938325";
  Line 10: 1	protein_coding	exon	11009681	11009871	.	-	.	gene_id "ENSG00000175262"; transcript_id "ENST00000418570"; exon_number "6"; gene_name "C1orf127"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "C1orf127-001"; transcript_source "havana"; exon_id "ENSE00001262890"; tag "cds_start_NF"; tag "mRNA_start_NF";
---
  - airway/inst/extdata/SRR1039508_subset.bam

--- Inspecting first 10 lines of airway/inst/extdata/SRR1039508_subset.bam within airway_1.28.0.tar.gz ---
  Line 1:      � BC ��V[��U^3'�3�D����~���03�3�
  Line 2: 2M͙q��5�XE&	f`�t�[OQ/"E��d��E�I��%!��������0����˷�^�޳�o��.�����7w
  Line 3: ����,~w�#�ɛ��������c�Fcݺ������ѱ����Dkvn��yr��l�G��[��l�o�Y��l�.6Zӭ���:-�4.���������������I��Fmz�9��b��i�`��љ֎���������lk�Ӭ�0]��?b�Q�
  Line 4: �&v���z���
  Line 5: v�z�`7�I��(A�r)��BG��0!JRaV��Hj��0�0u��ha�a���R�f�SnY�p)��ՈJ�d��� �
  Line 6: њ�v=����kbV�ͩ�\�Q߷�N�d1/�mC����|
  Line 7: I9R�Y=[C�K3-[7�t�-:6�R�T��
  Line 8: SM�3Qq��a��F���7L��J���J���{XIe��H*�&�-`O1/7�J_��	!Բ���;aS�1Yp�)oO���F ��K����ڤ#$p�m@V�NES�V8i�z2pn!��w�y�Ѓ��򬞍�;���POi2�F�I�գ*r̊�ӑ�"�gЂ_]G��u�8�xv,��r�aY��m_e�A�[\��Z�%c�8f͵���X���'M2.̅���V��<;?R�L�|��"�d'DJ��r�	��0��"�M�eT�6/�,��Y�`��,/B-��Z��Y�Mˎ���%��m� m*T�r����m�k�@I�E��^�,��<wWt�;BD��T��&��J�ܸk(�����~��n�L|9y�k6�et����F�=wa~^!�}��BEE�E�P����/nX~���$��
  Line 9: 7�
  Line 10: �h랢�
---
  - airway/inst/extdata/SRR1039509_subset.bam

--- Inspecting first 10 lines of airway/inst/extdata/SRR1039509_subset.bam within airway_1.28.0.tar.gz ---
  Line 1:      � BC ��V[��U^3'�3�D����~���03�3�
  Line 2: 2M͙q��5�XE&	f`�t�[OQ/"E��d��E�I��%!��������0����˷�^�޳�o��.�����7w
  Line 3: ����,~w�#�ɛ��������c�Fcݺ������ѱ����Dkvn��yr��l�G��[��l�o�Y��l�.6Zӭ���:-�4.���������������I��Fmz�9��b��i�`��љ֎���������lk�Ӭ�0]��?b�Q�
  Line 4: �&v���z���
  Line 5: v�z�`7�I��(A�r)��BG��0!JRaV��Hj��0�0u��ha�a���R�f�SnY�p)��ՈJ�d��� �
  Line 6: њ�v=����kbV�ͩ�\�Q߷�N�d1/�mC����|
  Line 7: I9R�Y=[C�K3-[7�t�-:6�R�T��
  Line 8: SM�3Qq��a��F���7L��J���J���{XIe��H*�&�-`O1/7�J_��	!Բ���;aS�1Yp�)oO���F ��K����ڤ#$p�m@V�NES�V8i�z2pn!��w�y�Ѓ��򬞍�;���POi2�F�I�գ*r̊�ӑ�"�gЂ_]G��u�8�xv,��r�aY��m_e�A�[\��Z�%c�8f͵���X���'M2.̅���V��<;?R�L�|��"�d'DJ��r�	��0��"�M�eT�6/�,��Y�`��,/B-��Z��Y�Mˎ���%��m� m*T�r����m�k�@I�E��^�,��<wWt�;BD��T��&��J�ܸk(�����~��n�L|9y�k6�et����F�=wa~^!�}��BEE�E�P����/nX~���$��
  Line 9: 7�
  Line 10: �h랢�
---
  - airway/inst/extdata/SRR1039512_subset.bam

--- Inspecting first 10 lines of airway/inst/extdata/SRR1039512_subset.bam within airway_1.28.0.tar.gz ---
  Line 1:      � BC ��V[��U^3'�3�D����~���03�3�
  Line 2: 2M͙q��5�XE&	f`�t�[OQ/"E��d��E�I��%!��������0����˷�^�޳�o��.�����7w
  Line 3: ����,~w�#�ɛ��������c�Fcݺ������ѱ�e�h��ʹ6O.4����~��Ж�����s3s#������Bk�5��Z�e�ǥ�:9�Z�>�]<�����;)q�(�M9�Q,R>����28:�ڱ��<�����m�Ub�������{���B�ݣ�ޡg�C�ݴ�?�̈́e�(F#J�\J.���%L��TE�07�+#�=L��5�DXx�h.�$²���[a��%\
  Line 4: -yD5��R+m�0�jC�f�]�"*-eƚ��}sj-�m����S!Y��|��Pf+�1�BRN�TqE����E���B0}��
  Line 5: �T2}}�TS�LT�o��.�Q*��
  Line 6: S���`@m�RF�k0��VR� �.�J��l�S�ˍ��׶~���g�CؔcLs��-�D���v���%g�6)	�v��c�SFє�N����[�����j^/����<�g#��>�!��B����cRd����"�t�����W������lݲN0����dXg"G�WE�{��W�9�w��,��Ys�i63�1�I��sa�g���+9��Ώ�9-S&g1�	�R���fBx9L!��v��@����1�l%X�$�ċP��({nӲc��z	�f["H����h��A�{�Z"P�gQ$F��)�*'�����b9���o�R<7�ʢl�d��"F��;_N���o(����G��G��W�r�`&��@Q�}<$"��y����)����E�M~C�/ں�(���=�����L��a �tz6�����ӏ>�ʛD���dp{�����k�+�)੕�)���ㅩ���WxSõ߾�ϛz��+L�6�a]�n���2�\�y����O��dp�5ޕ�'��FK���1oI����.�<�ɽ�ab��u��uiZn1��K�Eϻa���;�_��vV�i��{WA���
  Line 7: 7M
  Line 8: *^n��֯�U�-!�Y���	���B�Z­I��F�+�_K1��_&��y�˭ܽ���\_H��� �������-,-'�0��S���Q8�z���G�8��C��� ॥D*��2�b�#I ���c��z�ώ*����QU����W���J��9�xa�3=X��V\�B����> PK!�5p!�P����\xB�|�xa��	�<��bů�$64�@� ��w/�D-���N'zMU!�C�;����	�^]'8��'�\8U�V���x���7�\8Bq,/M ��x�
  Line 9: �ON'^���T��H lh�;����/j
  Line 10: �       � BC �G�}y�$�Y_��v�wwv�����*�2�/���0v��T�h�ek0��d��ݫ�ӭ������-�Zi��"`�1al���a9����,!-�����{y�|�U5��Lw�L�����>?V���<V;���]��x�z�C�ރ���������h1��tܟ���'௟�����V�o\�M+Z�U�W����f�:�kz�$v˵��{��k�u�u\��<a^�+�|�
---
  - airway/inst/extdata/SRR1039513_subset.bam

--- Inspecting first 10 lines of airway/inst/extdata/SRR1039513_subset.bam within airway_1.28.0.tar.gz ---
  Line 1:      � BC ��V[��U^3'�3�D����~���03�3�
  Line 2: 2M͙q��5�XE&	f`�t�[OQ/"E��d��E�I��%!��������0����˷�^�޳�o��.�����7w
  Line 3: ����,~w�#�ɛ��������c�Fcݺ������ѱ�e�h��ʹ6O.4����~��Ж�����s3s#������Bk�5��Z�e�ǥ�:9�Z�>�]<�����;)q�(�M9�Q,R>����28:�ڱ��<�����m�Ub�������{���B�ݣ�ޡg�C�ݴ�?�̈́e�(F#J�\J.���%L��TE�07�+#�=L��5�DXx�h.�$²���[a��%\
  Line 4: -yD5��R+m�0�jC�f�]�"*-eƚ��}sj-�m����S!Y��|��Pf+�1����,���!�%������`:�b�d*�����Ι�8z�0u]p�T���Bq%\�����r�`@�=����]$�L�����K��m��jY�����)ǘ,8攷'ZƉ�s#��%�K�XmR�8�6 �����)G+�4Y=8�yQ�;Լ^�A[eyV�FΝ}�C���4G#Ǥ��Q9fE���Q��3h��.���S�ٺe	�`<;�A�ɰ,�D��������-��s-Y
  Line 5: ��Z�lf,�c�&���zw�WrD	��)sZ�L>�@b�"�JC9̈́�r�BZ��&ׁ2*k��c\�,J�@I����y-Q�,ܦe�����̶D�6�*F��d	�B�6�D�$ϢH�r/SUN��+:�!"�r*Fi��^�xn�5�E�@�|�E�r�w&����5��2:PTgk#ʏ���0?���L���"�"xH(D����7,��Sv��ϋ����_�uOQF���{�߁a�b]� ���(�l�aM
  Line 6: -�}x�7)������ԝ���a��WzS�S+�SB��SA�gϯ�k�}{�7
  Line 7: ��;W�Nm8Zú��z��e�?�R�&����:����wk�+�'N^_�����cޒ�፫]h)x��{K�Ħ��h8���*�,��b�720�z��w�rO�w�wo�V[����
  Line 8: ����n�T���í_;��[B�w��gN_��[7�>��ˍ$V���b���L /��$�[�{9�����x!��A�����'�[XZNta��/��p��B�Ǐ$Rq]�/wA�KK�TLe&	��+F�@l���/��ܟ�����s]y��<4�x!ts$�gz�>,��)T!��6���/V!|@��B�k�B���%�����0����xz9	Ċ_�I lh(���s�&^8�Z��N ���B����w/<����N&"p�O$�p���$�w��B��o&�p��X�^<�@���j���N�0ם�*�0|5�@��rw"u�}�Hk��       � BC L���l�Yؒl�֕�nUݺ��<��}��gׄ$�~�t����6Y���8��2�e���rh�d<1!&�������3�d͌�BVf�A���V�$���{"�4���ϣ�5uՏ:������߯}gO������k>���]{���K�������^���p���&n4^-��|������fs�!g�暰
  Line 9: �l���mv�|C���Q�y�G�wx��GR���)Y�yاA�4$$�w<��}�)�4��Uۗݵ���ݵ~����7��e{wR�4���P���?�|TF�����4��l$]o6M�;ޭ7���(������}`���D(��������)~�\��4�^����n=�{ �M1��3����r:�5�]�6H��c�<�m�Ow�F�^?�����lqI&��I"M5�02�����_D@i|1ʂ2���~8F���������f}sZ�5N���<nm7�u.�k�lm��FZDH��A���������!D�����ga����i:����� ݲM�(I�h����:�[)�z�4�N)X@��P)	�Tt��b�.)��H�YF%?�0j��³G���h6�)�Ivg��-8�Fk�inw��f�iy֔dSSP}�,\H�ԁdH.d��5 ��p�P,�"��v�L}o59~���T�nM�ľLPo��V��fm���	�5��s>�K��f����<+=���){����8<�x����j8�OR@Ԁ���������ѐ��N6�<�QE
  Line 10: (%CiYW(�`@TP`�7�ZP"��類�����*�4QT���Y���Z%M��3��S��Tk���琶��iɎ�'!)F�\�����%{�	M�[x��é��|6Y
---
  - airway/inst/extdata/SRR1039516_subset.bam

--- Inspecting first 10 lines of airway/inst/extdata/SRR1039516_subset.bam within airway_1.28.0.tar.gz ---
  Line 1:      � BC ��V[��U^3'�3�D����~���03�3�
  Line 2: 2M͙q��5�XE&	f`�t�[OQ/"E��d��E�I��%!��������0����˷�^�޳�o��.�����7w
  Line 3: ����,~w�#�ɛ��������c�Fcݺ������ѱ�e�h��ʹ6O.4����~��Ж�����s3s#������Bk�5��Z�e�ǥ�:9�Z�>�]<�����;)q��M9�Q,R>����28:�ڱ��<�����m�Ub�������{���B�ݣ�ޡg�C�ݴ�?�̈́e�(F#J�\J.���%L�rI"�
  Line 4: �I������m",<L4V
  Line 5: aY�Lr�-��B�.��<�QC����SD�!Z3Ѯg��2cM����9���6��Vܩ�,�e�ma(����O!)'B�8��gs�c��e�f!���EǆX*����a��s&*��7L]�(����P\	W0��@)��5Ёa+�l�vI%�D��)���R�k[?!�Z���p�!l�1&�9�퉖q��D�|��3V��c�N�
  Line 6: ���)�h��
  Line 7: 'MVO�-D�C��5�z�VY�ճ�sg���i!M���1)�z�#
  Line 8: �"�t�����W������lݲN0����dXg"G�WE�{��W�9�w��,��Ys�i63�1�I��sa�g���+9��Ώ�9-S&g1�	�R���fBx9L!��v��@����1�l%X�$�ċP��({nӲc��z	�f["H����h��A�{�Z"P�gQ$F��)�*'�����b9���o�R<7�ʢl�d��"F��;_N���o(����G��G��W�r�`&��@Q�}<$"��y����)����E�M~C�/ں�(���=�����L��a �tz6�����ӏ>�ʛD���dp{�����k�+�)੕�)���ㅩ���WxSõ߾�ϛz��+L�6�a]�n���2�\�y����O��dp�5ޕ�'��FK���1oI����.�<�ɽ�ab��u��uiZn1��K�Eϻa���;�_��vV�i��{WA���
  Line 9: 7M
  Line 10: *^n��֯�U�-!�Y���	���B�Z­I��F�+�_K1��_&��y�˭ܽ���\_H��� �������-,-'�0��S���Q8�z���G�8��C��� ॥D*��2�b�#I ���c��z�ώ*����QU����W���J��9�xa�3=X��V\�B����> PK!�5p!�P����\xB�|�xa��	�<��bů�$64�@� ��w/�D-���N'zMU!�C�;����	�^]'8��'�\8U�V���x���7�\8Bq,/M ��x�
---
  - airway/inst/extdata/SRR1039517_subset.bam

--- Inspecting first 10 lines of airway/inst/extdata/SRR1039517_subset.bam within airway_1.28.0.tar.gz ---
  Line 1:      � BC ��V[��U^3'�3�D����~���03�3�

# Create full airway metadata

In [6]:
def parse_series_matrix_for_metadata(series_matrix_file_gz):
    data_lines = {}

    # Open file and parse data
    with gzip.open(series_matrix_file_gz, 'rt') as f:
        for line in f:
            line = line.strip()
            if line.startswith("!Sample_") or line.startswith("!Series_"):
                parts = line.split('\t')
                header = parts[0]
                values = [val.strip('"') for val in parts[1:]]
                if header not in data_lines:
                    data_lines[header] = []
                data_lines[header].append(values)
            elif line.startswith("!series_matrix_table_begin"):
                break

    num_samples = len(data_lines["!Sample_geo_accession"][0])
    all_samples_data = []

    # 
    for i in range(num_samples):
        sample_dict = {}
        sample_dict['geo_id'] = data_lines["!Sample_geo_accession"][0][i]

        treatments_raw = [item_list[i] for item_list in data_lines.get("!Sample_characteristics_ch1", []) if item_list[i].lower().startswith("treatment:")]
        cell_lines_raw = [item_list[i] for item_list in data_lines.get("!Sample_characteristics_ch1", []) if item_list[i].lower().startswith("cell line:")]
        
        if treatments_raw:
            sample_dict['treatment_protocol'] = treatments_raw[0].replace("treatment: ", "").strip()
        if cell_lines_raw:
            sample_dict['cell_line'] = cell_lines_raw[0].replace("cell line: ", "").strip()
        
        sra_relations = [item_list[i] for item_list in data_lines.get("!Sample_relation", []) if "SRA: https" in item_list[i]]
        if sra_relations:
            srx_match = re.search(r'SRX\d+', sra_relations[0])
            if srx_match:
                sample_dict['srx_id'] = srx_match.group(0)
        
        all_samples_data.append(sample_dict)
        
    return pd.DataFrame(all_samples_data)

In [7]:
# Extract metadata
series_matrix_file_gz = "GSE52778_series_matrix.txt.gz"
metadata_with_srx_df = parse_series_matrix_for_metadata(series_matrix_file_gz)
display(metadata_with_srx_df)

        geo_id       treatment_protocol cell_line     srx_id
0   GSM1275862                Untreated    N61311  SRX384345
1   GSM1275863            Dexamethasone    N61311  SRX384346
2   GSM1275864                Albuterol    N61311  SRX384347
3   GSM1275865  Albuterol_Dexamethasone    N61311  SRX384348
4   GSM1275866                Untreated   N052611  SRX384349
5   GSM1275867            Dexamethasone   N052611  SRX384350
6   GSM1275868                Albuterol   N052611  SRX384351
7   GSM1275869  Albuterol_Dexamethasone   N052611  SRX384352
8   GSM1275870                Untreated   N080611  SRX384353
9   GSM1275871            Dexamethasone   N080611  SRX384354
10  GSM1275872                Albuterol   N080611  SRX384355
11  GSM1275873  Albuterol_Dexamethasone   N080611  SRX384356
12  GSM1275874                Untreated   N061011  SRX384357
13  GSM1275875            Dexamethasone   N061011  SRX384358
14  GSM1275876                Albuterol   N061011  SRX384359
15  GSM1275877  Albuterol_Dexamethasone   N061011  SRX384360

Search for SRR ids are prefered to GEO ids since they provide direct access to raw sequencing data, whereas GEO ids only offer descriptive metadata about the experiments.

In [8]:
srr_ids_list = []
db = SRAweb()

for srx_id in tqdm(metadata_with_srx_df['srx_id'], desc="Fetching SRR ids"):
    if pd.isna(srx_id):
        srr_ids_list.append(None)
        continue
    # The sra_metadata call can raise exceptions, which the user wants to see if they occur
    df_srx = db.sra_metadata(srx_id, detailed=False) 
    if not df_srx.empty and 'run_accession' in df_srx.columns:
        srr_ids_list.append(df_srx['run_accession'].iloc[0])
    else:
        srr_ids_list.append(None) # Explicitly append None if no run_accession
        print(f"Warning: No run_accession found for SRX {srx_id} using pysradb.")
            
metadata_with_srx_df['srr_id'] = srr_ids_list
display(metadata_with_srx_df)

Fetching SRR ids: 100%|██████████| 16/16 [00:14<00:00,  1.07it/s]

        geo_id       treatment_protocol cell_line     srx_id      srr_id
0   GSM1275862                Untreated    N61311  SRX384345  SRR1039508
1   GSM1275863            Dexamethasone    N61311  SRX384346  SRR1039509
2   GSM1275864                Albuterol    N61311  SRX384347  SRR1039510
3   GSM1275865  Albuterol_Dexamethasone    N61311  SRX384348  SRR1039511
4   GSM1275866                Untreated   N052611  SRX384349  SRR1039512
5   GSM1275867            Dexamethasone   N052611  SRX384350  SRR1039513
6   GSM1275868                Albuterol   N052611  SRX384351  SRR1039514
7   GSM1275869  Albuterol_Dexamethasone   N052611  SRX384352  SRR1039515
8   GSM1275870                Untreated   N080611  SRX384353  SRR1039516
9   GSM1275871            Dexamethasone   N080611  SRX384354  SRR1039517
10  GSM1275872                Albuterol   N080611  SRX384355  SRR1039518
11  GSM1275873  Albuterol_Dexamethasone   N080611  SRX384356  SRR1039519
12  GSM1275874                Untreated   N061011  SRX384357  SRR1039520
13  GSM1275875            Dexamethasone   N061011  SRX384358  SRR1039521
14  GSM1275876                Albuterol   N061011  SRX384359  SRR1039522
15  GSM1275877  Albuterol_Dexamethasone   N061011  SRX384360  SRR1039523

Extract entrez gene ids from GEO annotations and convert as many as possible to ensembl gene ids since they have a more precise gene model representation.

In [9]:
# Build Entrez to Ensembl gene id map

annotation_file_gz = "Human.GRCh38.p13.annot.tsv.gz"
annotation_df = pd.read_csv(annotation_file_gz, sep='\t', low_memory=False)
print("Annotation DataFrame columns:", annotation_df.columns)

# Correct column names based on your inspection:
entrez_col_annot = 'GeneID'
ensembl_col_annot = 'EnsemblGeneID'

# Create the mapping dictionary
annotation_df[entrez_col_annot] = annotation_df[entrez_col_annot].astype(str)
annotation_df = annotation_df.dropna(subset=[entrez_col_annot, ensembl_col_annot])

# Filter for valid Ensembl Gene IDs
annotation_df = annotation_df[annotation_df[ensembl_col_annot].astype(str).str.startswith('ENSG')]

id_map_df = annotation_df[[entrez_col_annot, ensembl_col_annot]].drop_duplicates(subset=[entrez_col_annot], keep='first')
entrez_to_ensembl_map = pd.Series(id_map_df[ensembl_col_annot].values, index=id_map_df[entrez_col_annot]).to_dict()

print(f"Created Entrez to Ensembl map. Example items: {list(entrez_to_ensembl_map.items())[:5]}")

Annotation DataFrame columns: Index(['GeneID', 'Symbol', 'Description', 'Synonyms', 'GeneType',
       'EnsemblGeneID', 'Status', 'ChrAcc', 'ChrStart', 'ChrStop',
       'Orientation', 'Length', 'GOFunctionID', 'GOProcessID', 'GOComponentID',
       'GOFunction', 'GOProcess', 'GOComponent'],
      dtype='object')
Created Entrez to Ensembl map. Example items: [('100287102', 'ENSG00000290825'), ('102466751', 'ENSG00000278267'), ('100302278', 'ENSG00000284332'), ('645520', 'ENSG00000237613'), ('79501', 'ENSG00000186092')]

In [10]:
# Collect Entrez ids in dataset
raw_counts_file_gz = "GSE52778_raw_counts_GRCh38.p13_NCBI.tsv.gz"
raw_counts_df = pd.read_csv(raw_counts_file_gz, sep='\t')
raw_counts_df["GeneID"].head()

0    100287102
1       653635
2    102466751
3    107985730
4    100302278
Name: GeneID, dtype: int64

In [11]:
# Map Entrez to Ensembl gene id
raw_counts_df['GeneID'] = raw_counts_df['GeneID'].astype(str)
raw_counts_df['ensgene'] = raw_counts_df['GeneID'].map(entrez_to_ensembl_map)
raw_counts_df['ensgene'].head()

0    ENSG00000290825
1                NaN
2    ENSG00000278267
3                NaN
4    ENSG00000284332
Name: ensgene, dtype: object

In [12]:
# Drop unmappable ids
raw_counts_mapped_df = raw_counts_df.dropna(subset=['ensgene'])
raw_counts_df.head()

,GeneID,GSM1275862,GSM1275863,GSM1275864,GSM1275865,GSM1275866,GSM1275867,GSM1275868,GSM1275869,GSM1275870,GSM1275871,GSM1275872,GSM1275873,GSM1275874,GSM1275875,GSM1275876,GSM1275877,ensgene
0,100287102,6,8,8,3,5,10,11,7,6,8,4,10,2,1,2,2,ENSG00000290825
1,653635,357,292,351,285,469,428,523,442,367,415,404,354,371,381,367,341,NaN
2,102466751,12,11,12,10,15,15,19,15,9,11,18,9,10,9,12,6,ENSG00000278267
3,107985730,1,1,2,1,3,2,2,3,1,1,1,1,2,1,1,1,NaN
4,100302278,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1,ENSG00000284332

Use metadata to map GSM to SRR ids in our raw counts dataset.

In [13]:
# Rename GSM columns to SRR IDs
gsm_to_srr = dict(zip(metadata_with_srx_df['geo_id'], metadata_with_srx_df['srr_id']))
gsm_cols = [col for col in raw_counts_mapped_df.columns if col.startswith('GSM')]
raw_counts_mapped_df.rename(columns=gsm_to_srr, inplace=True)
raw_counts_mapped_df.head()

/tmp/ipykernel_151207/1488723805.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_counts_mapped_df.rename(columns=gsm_to_srr, inplace=True)

,GeneID,SRR1039508,SRR1039509,SRR1039510,SRR1039511,SRR1039512,SRR1039513,SRR1039514,SRR1039515,SRR1039516,SRR1039517,SRR1039518,SRR1039519,SRR1039520,SRR1039521,SRR1039522,SRR1039523,ensgene
0,100287102,6,8,8,3,5,10,11,7,6,8,4,10,2,1,2,2,ENSG00000290825
2,102466751,12,11,12,10,15,15,19,15,9,11,18,9,10,9,12,6,ENSG00000278267
4,100302278,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1,ENSG00000284332
5,645520,7,2,4,4,6,2,3,6,2,2,3,6,6,3,8,3,ENSG00000237613
6,79501,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ENSG00000186092

Expand Ensembl list of genes with empty gene list from expert crafted dataset by adding zeros to genes that aren't present in the data collected from GEO.

In [14]:
df_given = pd.read_csv("airway_rawcounts.csv")
df_given.head()

,ensgene,SRR1039508,SRR1039509,SRR1039512,SRR1039513,SRR1039516,SRR1039517,SRR1039520,SRR1039521
0,ENSG00000000003,679,448,873,408,1138,1047,770,572
1,ENSG00000000005,0,0,0,0,0,0,0,0
2,ENSG00000000419,467,515,621,365,587,799,417,508
3,ENSG00000000457,260,211,263,164,245,331,233,229
4,ENSG00000000460,60,55,40,35,78,63,76,60

In [15]:
# Add missing genes with zeros (takes time to run)
ensgene_list = df_given['ensgene'].tolist()
ensgene_set = set(ensgene_list)
existing_ensgenes = raw_counts_mapped_df['ensgene'].tolist()

srr_cols = [col for col in raw_counts_mapped_df.columns if col.startswith('SRR')]

for ensgene in ensgene_list:
    if (ensgene != 0) and (ensgene not in existing_ensgenes):
        new_row = {'ensgene': ensgene}
        for col in srr_cols:
            new_row[col] = 0
        new_row['GeneID'] = 0
        raw_counts_mapped_df = pd.concat([raw_counts_mapped_df, pd.DataFrame([new_row])], ignore_index=True)

In [16]:
# Clean up raw counts dataset
raw_counts_mapped_df_sorted = raw_counts_mapped_df.sort_values(by='ensgene')
raw_counts_mapped_df_sorted = raw_counts_mapped_df_sorted.drop(columns=['GeneID'])
ensgene_col = raw_counts_mapped_df_sorted.pop('ensgene')
raw_counts_mapped_df_sorted.insert(0, 'ensgene', ensgene_col)
raw_counts_mapped_df_sorted.head()

,ensgene,SRR1039508,SRR1039509,SRR1039510,SRR1039511,SRR1039512,SRR1039513,SRR1039514,SRR1039515,SRR1039516,SRR1039517,SRR1039518,SRR1039519,SRR1039520,SRR1039521,SRR1039522,SRR1039523
26462,ENSG00000000003,708,470,768,475,905,1088,1009,1093,1331,1093,1133,1646,1301,1018,1159,886
26461,ENSG00000000005,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0
24708,ENSG00000000419,464,517,458,527,620,939,885,560,663,799,727,721,701,868,550,689
1953,ENSG00000000457,313,250,279,276,325,482,399,349,353,407,352,344,466,485,314,344
1952,ENSG00000000460,115,108,145,119,115,179,179,140,172,156,131,150,195,192,157,160

In [17]:
raw_counts_mapped_df_sorted.to_csv('airway_rawcounts_more_exps.csv', index=False)
raw_counts_mapped_df_sorted.shape

(66188, 17)

In [18]:
# Clean up metadata
geo_id_col = metadata_with_srx_df.pop('geo_id')
metadata_with_srx_df['geo_id'] = geo_id_col

In [19]:
metadata_with_srx_df.to_csv('airway_metadata_more_exps.csv', index=False)
metadata_with_srx_df.shape

(16, 5)